import pandas as pd
ufo = pd.read_csv('http://bit.ly/uforeports')
print(ufo)
print(ufo.shape)
ufo.drop('Colors Reported', axis=1, inplace=True)
print(ufo.head())
ufo.drop(['City', 'State'], axis=1, inplace=True)
print(ufo.head())
ufo.drop([0, 1], axis=0, inplace=True)
print(ufo.head())
print(ufo.shape)
